### PR TITLE
Grahamdev

### PR DESCRIPTION
**Pull request by gmurray68w**
Graham's Pull request

### CODE REVIEW

**Comment by gmurray68w** [comment]
Has conflicts that need to be resolved

**Comment by Brandon-T-Yates** [comment]
@gmurray68w for your main.dart you need to remove all your code. main.dart is not configured yet so just copy past the main.dart from this repo to your branch then push. But I also noticed all your code seems to be in the main.dart file when it needs to be under the GUIE folder. Move it all to its own file and then test using main but then erase your main to match the main here on the repo. And when creating a file to code in do navbar.dart not just navbar. If you need help let me know I got you!

**Comment by gmurray68w** [comment]
Added the appropriate files and code for the top and bottom navigation bars, and the settings page which shouldn't be needed yet so I figured that should be separated as well.

Fixed the .dart extensions 

Made the main.dart match what was on Tyler's main.dart.

So, hopefully, that should set it back on track.

**Comment by Brandon-T-Yates** [comment]
Changed your main to match what was in the UI branches main but other than that it looks great!

**Pull request merged**
